module.exports = {
  darkMode: 'class',
  content: ['src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      Albert: ['Albert Sans', 'sans-serif'],
      Roboto: ['Roboto Slab', 'serif'],
      OpenSans: ['Open Sans', 'sans-serif'],
    },
    extend: {
      colors: {
        'off-white': '#F1F6F8',
        'teal-blue': '#90E0EF',
        'light-blue': '#83B0EC',
        'sky-blue': '#2F80ED',
        'dark-blue': '#184379',
        accent: '#FF841F',
        'off-black': '#0C0D0D',
        'htd-grey': '#A2ABAA',
        error: '#BC1723',
        success: '#60C95E',
        'off-white-dark': '#F2F6F8',
        'teal-blue-dark': '#90E0EF',
        'sky-blue-dark': '#83B0EC',
        'dark-blue-dark': '#255693',
        'accent-dark': '#D87C31',
        'light-black-dark': '#121212',
        'htd-grey-dark': '#A2ABAA',
        'dark-grey-dark': '#1F2123',
        'error-dark': '#B3202B',
        'success-dark': '#5BC059',
      },
    },
  },
  plugins: [],
}
